### ISSUE TITLE
Jenkins not triggered when pushing develop branch

### ISSUE THREAD

**Issue by pkrog** [phnmnl/docker-univariate#1]
When pushing new commits to develop branch, Jenkins job is not triggered.
Jenkins job is only triggered when pushing master branch.

**Comment by pkrog** [comment]
There was an error about the webhook that was displayed in Jenkins. I've deleted and then regenerated the webhook. However this does not solve the issue, and I've been able to see problem also with other repositories.
Thus it seems the issue is more general, and related to Jenkins itself.
@pcm32 , could you like at that in Jenkins when you have a moment, please? Maybe an update?

**Comment by pcm32** [comment]
Hi @pierrickrogermele I don't see this behaviour on other repos that I have been working lately. I'll take a look at it, thanks for flagging it up.

**Comment by pcm32** [comment]
I have taken a look at it, it was missing the section Source Code Management -> Git -> Additional behaviours -> Check out specific local branch with no Branch name. This is something I remember you pointed out in the past. Give it a try now, it should work.

**Comment by pcm32** [comment]
I think that this is done, so I'll close it. Let me know if it needs re-open.
